language: python

python:
 - "3.5"

addons:
 apt:
  packages:
   - oracle-java8-installer

before_script:
 - wget http://central.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.jar
 - echo '#!/bin/bash' > clojure.sh
 - echo 'java -jar clojure-1.8.0.jar $@' >> clojure.sh
 - chmod +x clojure.sh

script: AB_CLOJURE="./clojure.sh" make libexec test