language: python

python:
 - "3.5"

install:
 - pip install coverage
 - pip install codecov
 - pip install -r requirements.txt

addons:
 apt:
  packages:
   - oracle-java8-installer

before_script:
 - wget http://central.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.jar
 - echo '#!/bin/bash' > clojure.sh
 - echo 'java -jar clojure-1.8.0.jar $@' >> clojure.sh
 - chmod +x clojure.sh

script: AB_JAVA="/usr/lib/jvm/java-8-oracle/jre/bin/java" AB_CLOJURE="./clojure.sh" make PYTHON=~/virtualenv/python3.5/bin/python libexec .coverage

after_success:
 - codecov
